### PR TITLE
Add metadata discovery & resolution paths to escrow contracts

### PR DESCRIPTION
**Pull request by sisyphusSmiling**
Closes:  #112 cc: @bjartek
Related: #99 

> ℹ️ Cadence CI seems to be failing on CLI install because there was a [recent release](https://github.com/onflow/flow-cli/releases/tag/v1.21.0-cadence-v1.0.0-preview.38) of Flow CLI which isn't yet available. I'll run CI again after some time to confirm passing tests.

## Description

- Enhances error messages in escrow contracts & scripts
- Adds the ability to discover supported metadata views from NFTs in locked in escrow
- Adds supporting scripts for new and existing escrow functionality

______

For contributor use:

- [x] Targeted PR against `main` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-evm-bridge/blob/master/CONTRIBUTING.md#styleguides).
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by joshuahannan — APPROVED** [review]
Beautiful error messages! 👏 🥳

**Comment by bjartek** [comment]
Would it be possible to have a method here to get do the two following things?

https://github.com/onflow/flow-nft/blob/0ce4125dcb5c351c64706edd5b210d1e22691ef5/contracts/NonFungibleToken.cdc#L123

and to get the views and resolve them for subnfts aswell?

Maybe that is another issue. Granted not very many people have subnfts that are bridge but it would still be nice to have if that ever happends.

**Review by bjartek — APPROVED** [review]

**Comment by sisyphusSmiling** [comment]
@bjartek updated based on recent convos (thanks for sharing!) and created #115 to add support for sub-NFTs

**Review by bjartek — APPROVED** [review]

**Comment by sisyphusSmiling** [comment]
Merging in preparation for mainnet migration test today, but feel free to review and request changes after the fact @joshuahannan

**Pull request merged**
