### PR TITLE
Polish bridge contract events for traceability & readability

### PR DESCRIPTION
**Pull request by sisyphusSmiling**
Closes: #65 

## Description

Updates bridge events to include values common in NFT & FT standards which enhance asset traceability. Also moving from emitting Cadence Type values to more human-readable type identifier strings.

______

For contributor use:

- [x] Targeted PR against `main` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-evm-bridge/blob/master/CONTRIBUTING.md#styleguides).
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by sisyphusSmiling** [comment]
cc @bjartek

**Review by joshuahannan — APPROVED** [review]
looks good to me if Bjarte is okay with it!

**Comment by bjartek** [comment]
Yeah this works!

**Comment by sisyphusSmiling** [comment]
Added some minor changes added in [700dfe4](https://github.com/onflow/flow-evm-bridge/pull/89/commits/700dfe4b8e08a968e00c9398f774a06d2a072896) - changing from event type `Type` to string and adding uuid where traceability is relevant.

**Review by ramtinms — APPROVED** [review]

**Pull request merged**
